### ISSUE TITLE
Suggesting moves for the wrong colour if players move flats relatively early in the game

### ISSUE THREAD

**Issue by nitzel** [Skoolin/TAKexplorer#5]
Tones: 
> speaking of asymmetry (in ⁠tak_general ), I noticed an issue with the opening explorer. It messed up transpositions where you get the same position but different player to move.
> for example, after 
`1. f6 a6 2. a6-`
it will include games like 
`1. f6 a5`
which is very different

nitzel:
>Well spotted. If a player moves a flat from one field to another in the early moves, the suggested moves have the wrong color. I think we may need to store who's turn it is with each position to fix that. What do you think, @Skoolin ?
Checkout what happens to the suggested moves when doing move 5 for white and then for black, even though I chose a move with "96 games" for black.

https://ptn.ninja/NoZQlgLgpgBARABQDYEMCeAVFBrAdAYwHsBbOAXQFgAoYAUQDcoA7CeAeSaTCdmXXOrAASlADOAVySs4AMQC0ABgE1wAL1hwAbMuABhJIXzZ4ARgUAuBTADUAJiWUaAaRJh4tnWwAOzbgHN4UQB3FC9lahNcGAAzTRgUTWpbKPwAFhgAE1TqAGYogCMczJzqVJSAVkzy6nKCnIA+GHxbGABvWoIWsFEYACcoImJiZgyoDJh8tBgIAAtYQh8mfxgoAA8vA37emCDIGZgATji-FGGeuQnxViC5pgnUIxgN9B7IABppuf7476ZCGGIhG+xBQEHwM2WJzOuAAvkA&name=GwD2AICMCcFMEMDWBLAdgc3AFwBa3APYAOsqamsIRANgXNEA&ply=7!

**Comment by nitzel** [comment]
Either who's turn it is, stored on the position, or store the acting player's color with the moves that are applied to that position.

**Comment by Skoolin** [comment]
I think storing side to move in the position makes the most sense because the positions are actually different, not just the moves.
